name: Calculate (some) DORA metrics
on: workflow_dispatch
jobs:
  calculate-dora-metrics:
      runs-on: ubuntu-latest
      name: Calculate Lead time for changes & Deployment frequency
      steps:
        - uses: DeveloperMetrics/lead-time-for-changes@main
          with:
            workflows: 'CI'
        - uses: DeveloperMetrics/deployment-frequency@main
          with:
            workflows: 'CI'
